export const types = {
    // issues.controller - getIssues
    LIST_ISSUES: 'ISSUES/LIST/REQUEST',
    LIST_ISSUES_SUCCESS: 'ISSUES/LIST/SUCCESS',
    LIST_ISSUES_FAILURE: 'ISSUES/LIST/FAILURE',
    // issues.controller - getIssueById
    GET_ISSUES: 'ISSUES/GET/REQUEST',
    GET_ISSUES_SUCCESS: 'ISSUES/GET/SUCCESS',
    GET_ISSUES_FAILURE: 'ISSUES/GET/FAILURE',
    // issues.controller - createIssue
    CREATE_ISSUES: 'ISSUES/CREATE/REQUEST',
    CREATE_ISSUES_SUCCESS: 'ISSUES/CREATE/SUCCESS',
    CREATE_ISSUES_FAILURE: 'ISSUES/CREATE/FAILURE',
    // issues.controller - updateIssue
    UPDATE_ISSUES: 'ISSUES/UPDATE/REQUEST',
    UPDATE_ISSUES_SUCCESS: 'ISSUES/UPDATE/SUCCESS',
    UPDATE_ISSUES_FAILURE: 'ISSUES/UPDATE/FAILURE'
};
