export const types = {
    // penalties.controller - getPenalties
    LIST_PENALTIES: 'PENALTIES/LIST/REQUEST',
    LIST_PENALTIES_SUCCESS: 'PENALTIES/LIST/SUCCESS',
    LIST_PENALTIES_FAILURE: 'PENALTIES/LIST/FAILURE',
    // penalties.controller - getPenaltyById
    GET_PENALTIES: 'PENALTIES/GET/REQUEST',
    GET_PENALTIES_SUCCESS: 'PENALTIES/GET/SUCCESS',
    GET_PENALTIES_FAILURE: 'PENALTIES/GET/FAILURE',
    // penalties.controller - createPenalty
    CREATE_PENALTIES: 'PENALTIES/CREATE/REQUEST',
    CREATE_PENALTIES_SUCCESS: 'PENALTIES/CREATE/SUCCESS',
    CREATE_PENALTIES_FAILURE: 'PENALTIES/CREATE/FAILURE',
    // penaltiescontroller - updatePenalty
    UPDATE_PENALTIES: 'PENALTIES/UPDATE/REQUEST',
    UPDATE_PENALTIES_SUCCESS: 'PENALTIES/UPDATE/SUCCESS',
    UPDATE_PENALTIES_FAILURE: 'PENALTIES/UPDATE/FAILURE'
};
