import { Offense } from './offenses.model';

export const types = {
    // offenses.controller - getoffenses
    LIST_OFFENSES: 'OFFENSES/LIST/REQUEST',
    LIST_OFFENSES_SUCCESS: 'OFFENSES/LIST/SUCCESS',
    LIST_OFFENSES_FAILURE: 'OFFENSES/LIST/FAILURE',
    // offenses.controller - getoffenseById
    GET_OFFENSES: 'OFFENSES/GET/REQUEST',
    GET_OFFENSES_SUCCESS: 'OFFENSES/GET/SUCCESS',
    GET_OFFENSES_FAILURE: 'OFFENSES/GET/FAILURE',
    // offenses.controller - createOffense
    CREATE_OFFENSES: 'OFFENSES/CREATE/REQUEST',
    CREATE_OFFENSES_SUCCESS: 'OFFENSES/CREATE/SUCCESS',
    CREATE_OFFENSES_FAILURE: 'OFFENSES/CREATE/FAILURE',
    // offenses.controller - updateOffense
    UPDATE_OFFENSES: 'OFFENSES/UPDATE/REQUEST',
    UPDATE_OFFENSES_SUCCESS: 'OFFENSES/UPDATE/SUCCESS',
    UPDATE_OFFENSES_FAILURE: 'OFFENSES/UPDATE/FAILURE'
};
