export const types = {
    // users.controller - getUsers
    LIST_USERS: 'USERS/LIST/REQUEST',
    LIST_USERS_SUCCESS: 'USERS/LIST/SUCCESS',
    LIST_USERS_FAILURE: 'USERS/LIST/FAILURE',
    // users.controller - getUserById
    GET_USERS: 'USERS/GET/REQUEST',
    GET_USERS_SUCCESS: 'USERS/GET/SUCCESS',
    GET_USERS_FAILURE: 'USERS/GET/FAILURE',
    // userss.controller - createUser
    CREATE_USERS: 'USERS/CREATE/REQUEST',
    CREATE_USERS_SUCCESS: 'USERS/CREATE/SUCCESS',
    CREATE_USERS_FAILURE: 'USERS/CREATE/FAILURE',
    // userss.controller - updateUser
    UPDATE_USERS: 'USERS/UPDATE/REQUEST',
    UPDATE_USERS_SUCCESS: 'USERS/UPDATE/SUCCESS',
    UPDATE_USERS_FAILURE: 'USERS/UPDATE/FAILURE'
};
